Update main
increasing memory requirement of the app so that I can run large fmri data.

From HCP/pRF
``` 
Error: cannot allocate vector of size 23.3 Gb
Execution halted
```